### PR TITLE
Fix disk state evaluation and add the shebang line

### PR DESCRIPTION
**Pull request by Doomas**
Hi

Disk state fix:
adding the disk states with `+=` results in an Array of single letters. Therefore the final disk state was in every case "UNKOWN". With `states.append()` it works as intended.

Shebang:
The script was not automatically execute on my servers without the shebang

Regards Thomas

### CODE REVIEW

**Comment by wernerfred** [comment]
Change was introduced in #28 by @amotl - can you have a look too please?

**Comment by Doomas** [comment]
Ok, I've checked it, and I think this a bug.

To append a entire String to an array you should use `states.append()`(I think this is the faster operation) or `states += ["STATE"]` (with square brackets).

But I like to know if this works for @amotl

**Comment by Kraeutergarten** [comment]
I can confirm this BUG. Please use append and add a python3 shebang.

**Comment by wernerfred** [comment]
@all-contributors add @Doomas for code

**Comment by wernerfred** [comment]
@all-contributors please add @Kraeutergarten for User Testing

**Comment by amotl** [comment]
Hi there,

it definitively looks like that I made a mistake here. Apologies. Thank you very much for discovering and fixing this, @Doomas!

@wernerfred: I think it is ready to be merged. Go ahead!

With kind regards,
Andreas.

**Pull request merged**
