### PR TITLE
Introduce support for 'disk health' value

### PR DESCRIPTION
**Pull request by p-try**
Fixes https://github.com/wernerfred/check_synology/issues/56

### CODE REVIEW

**Review by wernerfred — CHANGES_REQUESTED** [review]
LGTM 👍🏻 

Can you please update the `README.md` as well that the disk check also supports health status?

**Comment by wernerfred** [comment]
@all-contributors please add @p-try for code

**Comment by wernerfred** [comment]
@all-contributors please add @p-try for code now

**Comment by p-try** [comment]
> LGTM 👍🏻
> 
> Can you please update the `README.md` as well that the disk check also supports health status?

Of course, thanks for following up!

**Review by wernerfred — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
